name: Portfolio App
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Portfolio App
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
      - run: cd build/web
      - run: git init
      - run: git config --global user.email benjaminudoh10@gmail.com
      - run: git config --global user.name Benjamin Udoh
      - run: git status
      # - run: git remote add origin https://${{secrets.commit_secret}}@github.com/benjaminudoh10/portfolio.git
      - run: git checkout -b gh-pages
      - run: git add --all
      # - run: git commit -m "update"
      - run: git push origin gh-pages -f
